from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from .views import BookViewSet, RegisterView

# A router automatically generates the CRUD routes for our ViewSet
router = DefaultRouter()
router.register(r'books', BookViewSet, basename='book')

urlpatterns = [
    # Include the CRUD routes generated by the router
    path('', include(router.urls)),
    
    # Registration endpoint
    path('register/', RegisterView.as_view(), name='register'),
    
    # Login endpoint (Django REST Framework's built-in view for generating tokens)
    path('login/', obtain_auth_token, name='login'),
]